# coding: utf-8

"""
    The ESnet Janus container API

    REST endpoints for container provisioning and tuning

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from janus_py_client.models.session_request_list import SessionRequestList

class TestSessionRequestList(unittest.TestCase):
    """SessionRequestList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionRequestList:
        """Test SessionRequestList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionRequestList`
        """
        model = SessionRequestList()
        if include_optional:
            return SessionRequestList(
                arguments = '',
                constraints = { },
                image = '',
                instances = [
                    null
                    ],
                kwargs = { },
                name = '',
                overrides = { },
                profile = '',
                remove_container = True
            )
        else:
            return SessionRequestList(
                image = '',
                instances = [
                    null
                    ],
                profile = '',
        )
        """

    def testSessionRequestList(self):
        """Test SessionRequestList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
