# coding: utf-8

"""
    The ESnet Janus container API

    REST endpoints for container provisioning and tuning

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from janus_py_client.api.janus_controller_api import JanusControllerApi


class TestJanusControllerApi(unittest.TestCase):
    """JanusControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JanusControllerApi()

    def tearDown(self) -> None:
        pass

    def test_controller_add_node_nodes_post(self) -> None:
        """Test case for controller_add_node_nodes_post

        Add a new node
        """
        pass

    def test_controller_check_token_token_get(self) -> None:
        """Test case for controller_check_token_token_get

        Check Token
        """
        pass

    def test_controller_create_sessions_create_post(self) -> None:
        """Test case for controller_create_sessions_create_post

        Create one or more new sessions.
        """
        pass

    def test_controller_delete_active_active_int_aid_delete(self) -> None:
        """Test case for controller_delete_active_active_int_aid_delete

        Delete a specific active session
        """
        pass

    def test_controller_delete_auth_auth_path_resource_int_rid_delete(self) -> None:
        """Test case for controller_delete_auth_auth_path_resource_int_rid_delete

        Delete auth info by ID
        """
        pass

    def test_controller_delete_auth_auth_path_resource_path_rname_delete(self) -> None:
        """Test case for controller_delete_auth_auth_path_resource_path_rname_delete

        Delete auth info by name
        """
        pass

    def test_controller_delete_node_nodes_int_id_delete(self) -> None:
        """Test case for controller_delete_node_nodes_int_id_delete

        Delete node by ID
        """
        pass

    def test_controller_delete_node_nodes_node_delete(self) -> None:
        """Test case for controller_delete_node_nodes_node_delete

        Delete node by name
        """
        pass

    def test_controller_delete_profile_profiles_path_resource_path_rname_delete(self) -> None:
        """Test case for controller_delete_profile_profiles_path_resource_path_rname_delete

        Remove a profile
        """
        pass

    def test_controller_exec_command_exec_post(self) -> None:
        """Test case for controller_exec_command_exec_post

        Execute a container command inside an active session.
        """
        pass

    def test_controller_get_active_active_get(self) -> None:
        """Test case for controller_get_active_active_get

        Get all active sessions
        """
        pass

    def test_controller_get_active_by_id_active_int_aid_get(self) -> None:
        """Test case for controller_get_active_by_id_active_int_aid_get

        Get a specific active session
        """
        pass

    def test_controller_get_auth_auth_path_resource_get(self) -> None:
        """Test case for controller_get_auth_auth_path_resource_get

        Get auth info
        """
        pass

    def test_controller_get_auth_auth_path_resource_int_rid_get(self) -> None:
        """Test case for controller_get_auth_auth_path_resource_int_rid_get

        Get specific auth info by ID
        """
        pass

    def test_controller_get_auth_auth_path_resource_path_rname_get(self) -> None:
        """Test case for controller_get_auth_auth_path_resource_path_rname_get

        Get specific auth info by name
        """
        pass

    def test_controller_get_images_images_get(self) -> None:
        """Test case for controller_get_images_images_get

        Get images
        """
        pass

    def test_controller_get_images_images_path_name_get(self) -> None:
        """Test case for controller_get_images_images_path_name_get

        Get a specific image
        """
        pass

    def test_controller_get_logs_active_int_aid_logs_path_nname_get(self) -> None:
        """Test case for controller_get_logs_active_int_aid_logs_path_nname_get

        Display logs for a specific active session and node.
        """
        pass

    def test_controller_get_node_by_id_or_name_nodes_int_id_get(self) -> None:
        """Test case for controller_get_node_by_id_or_name_nodes_int_id_get

        Get node by ID
        """
        pass

    def test_controller_get_node_by_id_or_name_nodes_node_get(self) -> None:
        """Test case for controller_get_node_by_id_or_name_nodes_node_get

        Get node by name
        """
        pass

    def test_controller_get_nodes_nodes_get(self) -> None:
        """Test case for controller_get_nodes_nodes_get

        Get nodes
        """
        pass

    def test_controller_get_profile_by_name_profiles_path_resource_path_rname_get(self) -> None:
        """Test case for controller_get_profile_by_name_profiles_path_resource_path_rname_get

        Get a specific profile
        """
        pass

    def test_controller_get_profiles_by_resource_profiles_path_resource_get(self) -> None:
        """Test case for controller_get_profiles_by_resource_profiles_path_resource_get

        Get profiles for a resource
        """
        pass

    def test_controller_get_profiles_default_profiles_get(self) -> None:
        """Test case for controller_get_profiles_default_profiles_get

        Get host profiles (default)
        """
        pass

    def test_controller_get_token_token_post(self) -> None:
        """Test case for controller_get_token_token_post

        Get Token
        """
        pass

    def test_controller_post_active_apply_active_int_aid_apply_post(self) -> None:
        """Test case for controller_post_active_apply_active_int_aid_apply_post

        Apply changes to a session
        """
        pass

    def test_controller_post_auth_auth_path_resource_int_rid_post(self) -> None:
        """Test case for controller_post_auth_auth_path_resource_int_rid_post

        Update auth info by ID
        """
        pass

    def test_controller_post_auth_auth_path_resource_path_rname_post(self) -> None:
        """Test case for controller_post_auth_auth_path_resource_path_rname_post

        Update auth info by name
        """
        pass

    def test_controller_post_auth_bulk_auth_bulk_post(self) -> None:
        """Test case for controller_post_auth_bulk_auth_bulk_post

        Bulk update auth info
        """
        pass

    def test_controller_post_profile_profiles_path_resource_path_rname_post(self) -> None:
        """Test case for controller_post_profile_profiles_path_resource_path_rname_post

        Create a new profile
        """
        pass

    def test_controller_put_active_active_int_aid_put(self) -> None:
        """Test case for controller_put_active_active_int_aid_put

        Update a specific active session
        """
        pass

    def test_controller_put_profile_profiles_path_resource_path_rname_put(self) -> None:
        """Test case for controller_put_profile_profiles_path_resource_path_rname_put

        Update a profile
        """
        pass

    def test_controller_start_session_endpoint_start_int_aid_put(self) -> None:
        """Test case for controller_start_session_endpoint_start_int_aid_put

        Start a container service by id.
        """
        pass

    def test_controller_stop_session_endpoint_stop_int_aid_put(self) -> None:
        """Test case for controller_stop_session_endpoint_stop_int_aid_put

        Stop a container service by id.
        """
        pass


if __name__ == '__main__':
    unittest.main()
