# coding: utf-8

"""
    The ESnet Janus container API

    REST endpoints for container provisioning and tuning

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from janus_py_client.api.nodes_api import NodesApi


class TestNodesApi(unittest.TestCase):
    """NodesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NodesApi()

    def tearDown(self) -> None:
        pass

    def test_controller_add_node_nodes_post(self) -> None:
        """Test case for controller_add_node_nodes_post

        Add a new node
        """
        pass

    def test_controller_delete_node_nodes_int_id_delete(self) -> None:
        """Test case for controller_delete_node_nodes_int_id_delete

        Delete node by ID
        """
        pass

    def test_controller_delete_node_nodes_node_delete(self) -> None:
        """Test case for controller_delete_node_nodes_node_delete

        Delete node by name
        """
        pass

    def test_controller_get_node_by_id_or_name_nodes_int_id_get(self) -> None:
        """Test case for controller_get_node_by_id_or_name_nodes_int_id_get

        Get node by ID
        """
        pass

    def test_controller_get_node_by_id_or_name_nodes_node_get(self) -> None:
        """Test case for controller_get_node_by_id_or_name_nodes_node_get

        Get node by name
        """
        pass

    def test_controller_get_nodes_nodes_get(self) -> None:
        """Test case for controller_get_nodes_nodes_get

        Get nodes
        """
        pass


if __name__ == '__main__':
    unittest.main()
