# coding: utf-8

"""
    The ESnet Janus container API

    REST endpoints for container provisioning and tuning

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from janus_py_client.models.identifiers_inner import IdentifiersInner

class TestIdentifiersInner(unittest.TestCase):
    """IdentifiersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentifiersInner:
        """Test IdentifiersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdentifiersInner`
        """
        model = IdentifiersInner()
        if include_optional:
            return IdentifiersInner(
            )
        else:
            return IdentifiersInner(
        )
        """

    def testIdentifiersInner(self):
        """Test IdentifiersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
