# coding: utf-8

"""
    The ESnet Janus container API

    REST endpoints for container provisioning and tuning

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from janus_py_client.api.sessions_api import SessionsApi


class TestSessionsApi(unittest.TestCase):
    """SessionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SessionsApi()

    def tearDown(self) -> None:
        pass

    def test_controller_create_sessions_create_post(self) -> None:
        """Test case for controller_create_sessions_create_post

        Create one or more new sessions.
        """
        pass

    def test_controller_delete_active_active_int_aid_delete(self) -> None:
        """Test case for controller_delete_active_active_int_aid_delete

        Delete a specific active session
        """
        pass

    def test_controller_exec_command_exec_post(self) -> None:
        """Test case for controller_exec_command_exec_post

        Execute a container command inside an active session.
        """
        pass

    def test_controller_get_active_active_get(self) -> None:
        """Test case for controller_get_active_active_get

        Get all active sessions
        """
        pass

    def test_controller_get_active_by_id_active_int_aid_get(self) -> None:
        """Test case for controller_get_active_by_id_active_int_aid_get

        Get a specific active session
        """
        pass

    def test_controller_get_logs_active_int_aid_logs_path_nname_get(self) -> None:
        """Test case for controller_get_logs_active_int_aid_logs_path_nname_get

        Display logs for a specific active session and node.
        """
        pass

    def test_controller_post_active_apply_active_int_aid_apply_post(self) -> None:
        """Test case for controller_post_active_apply_active_int_aid_apply_post

        Apply changes to a session
        """
        pass

    def test_controller_put_active_active_int_aid_put(self) -> None:
        """Test case for controller_put_active_active_int_aid_put

        Update a specific active session
        """
        pass

    def test_controller_start_session_endpoint_start_int_aid_put(self) -> None:
        """Test case for controller_start_session_endpoint_start_int_aid_put

        Start a container service by id.
        """
        pass

    def test_controller_stop_session_endpoint_stop_int_aid_put(self) -> None:
        """Test case for controller_stop_session_endpoint_stop_int_aid_put

        Stop a container service by id.
        """
        pass


if __name__ == '__main__':
    unittest.main()
