# coding: utf-8

"""
    The ESnet Janus container API

    REST endpoints for container provisioning and tuning

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from janus_py_client.api.profiles_api import ProfilesApi


class TestProfilesApi(unittest.TestCase):
    """ProfilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProfilesApi()

    def tearDown(self) -> None:
        pass

    def test_controller_delete_profile_profiles_path_resource_path_rname_delete(self) -> None:
        """Test case for controller_delete_profile_profiles_path_resource_path_rname_delete

        Remove a profile
        """
        pass

    def test_controller_get_profile_by_name_profiles_path_resource_path_rname_get(self) -> None:
        """Test case for controller_get_profile_by_name_profiles_path_resource_path_rname_get

        Get a specific profile
        """
        pass

    def test_controller_get_profiles_by_resource_profiles_path_resource_get(self) -> None:
        """Test case for controller_get_profiles_by_resource_profiles_path_resource_get

        Get profiles for a resource
        """
        pass

    def test_controller_get_profiles_default_profiles_get(self) -> None:
        """Test case for controller_get_profiles_default_profiles_get

        Get host profiles (default)
        """
        pass

    def test_controller_post_profile_profiles_path_resource_path_rname_post(self) -> None:
        """Test case for controller_post_profile_profiles_path_resource_path_rname_post

        Create a new profile
        """
        pass

    def test_controller_put_profile_profiles_path_resource_path_rname_put(self) -> None:
        """Test case for controller_put_profile_profiles_path_resource_path_rname_put

        Update a profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
