# coding: utf-8

"""
    The ESnet Janus container API

    REST endpoints for container provisioning and tuning

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from janus_py_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_controller_check_token_token_get(self) -> None:
        """Test case for controller_check_token_token_get

        Check Token
        """
        pass

    def test_controller_get_token_token_post(self) -> None:
        """Test case for controller_get_token_token_post

        Get Token
        """
        pass


if __name__ == '__main__':
    unittest.main()
