# coding: utf-8

"""
    The ESnet Janus container API

    REST endpoints for container provisioning and tuning

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from janus_py_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_controller_delete_auth_auth_path_resource_int_rid_delete(self) -> None:
        """Test case for controller_delete_auth_auth_path_resource_int_rid_delete

        Delete auth info by ID
        """
        pass

    def test_controller_delete_auth_auth_path_resource_path_rname_delete(self) -> None:
        """Test case for controller_delete_auth_auth_path_resource_path_rname_delete

        Delete auth info by name
        """
        pass

    def test_controller_get_auth_auth_path_resource_get(self) -> None:
        """Test case for controller_get_auth_auth_path_resource_get

        Get auth info
        """
        pass

    def test_controller_get_auth_auth_path_resource_int_rid_get(self) -> None:
        """Test case for controller_get_auth_auth_path_resource_int_rid_get

        Get specific auth info by ID
        """
        pass

    def test_controller_get_auth_auth_path_resource_path_rname_get(self) -> None:
        """Test case for controller_get_auth_auth_path_resource_path_rname_get

        Get specific auth info by name
        """
        pass

    def test_controller_post_auth_auth_path_resource_int_rid_post(self) -> None:
        """Test case for controller_post_auth_auth_path_resource_int_rid_post

        Update auth info by ID
        """
        pass

    def test_controller_post_auth_auth_path_resource_path_rname_post(self) -> None:
        """Test case for controller_post_auth_auth_path_resource_path_rname_post

        Update auth info by name
        """
        pass

    def test_controller_post_auth_bulk_auth_bulk_post(self) -> None:
        """Test case for controller_post_auth_bulk_auth_bulk_post

        Bulk update auth info
        """
        pass


if __name__ == '__main__':
    unittest.main()
