# coding: utf-8

"""
    The ESnet Janus container API

    REST endpoints for container provisioning and tuning

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from janus_py_client.api.images_api import ImagesApi


class TestImagesApi(unittest.TestCase):
    """ImagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImagesApi()

    def tearDown(self) -> None:
        pass

    def test_controller_get_images_images_get(self) -> None:
        """Test case for controller_get_images_images_get

        Get images
        """
        pass

    def test_controller_get_images_images_path_name_get(self) -> None:
        """Test case for controller_get_images_images_path_name_get

        Get a specific image
        """
        pass


if __name__ == '__main__':
    unittest.main()
