# coding: utf-8

"""
    The ESnet Janus container API

    REST endpoints for container provisioning and tuning

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from janus_py_client.api.janus_agent_api import JanusAgentApi


class TestJanusAgentApi(unittest.TestCase):
    """JanusAgentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JanusAgentApi()

    def tearDown(self) -> None:
        pass

    def test_agent_delete_tc_netem_tc_netem_delete(self) -> None:
        """Test case for agent_delete_tc_netem_tc_netem_delete

        Delete netem rules
        """
        pass

    def test_agent_delete_tc_pacing_tc_pacing_delete(self) -> None:
        """Test case for agent_delete_tc_pacing_tc_pacing_delete

        Delete pacing rules
        """
        pass

    def test_agent_get_node_node_get(self) -> None:
        """Test case for agent_get_node_node_get

        Returns static node resources
        """
        pass

    def test_agent_get_tc_delay_tc_delay_get(self) -> None:
        """Test case for agent_get_tc_delay_tc_delay_get

        Get delay rules
        """
        pass

    def test_agent_get_tc_filter_tc_filter_get(self) -> None:
        """Test case for agent_get_tc_filter_tc_filter_get

        Get filter rules
        """
        pass

    def test_agent_get_tc_latency_tc_latency_get(self) -> None:
        """Test case for agent_get_tc_latency_tc_latency_get

        Get latency rules
        """
        pass

    def test_agent_get_tc_netem_tc_netem_get(self) -> None:
        """Test case for agent_get_tc_netem_tc_netem_get

        Get netem rules
        """
        pass

    def test_agent_get_tc_pacing_tc_pacing_get(self) -> None:
        """Test case for agent_get_tc_pacing_tc_pacing_get

        Get pacing rules
        """
        pass

    def test_agent_get_tune_endpoint_tune_get(self) -> None:
        """Test case for agent_get_tune_endpoint_tune_get

        Get node tuning settings
        """
        pass

    def test_agent_post_tc_delay_tc_delay_post(self) -> None:
        """Test case for agent_post_tc_delay_tc_delay_post

        Set delay rules
        """
        pass

    def test_agent_post_tc_filter_tc_filter_post(self) -> None:
        """Test case for agent_post_tc_filter_tc_filter_post

        Set filter rules
        """
        pass

    def test_agent_post_tc_latency_tc_latency_post(self) -> None:
        """Test case for agent_post_tc_latency_tc_latency_post

        Set latency rules
        """
        pass

    def test_agent_post_tc_netem_tc_netem_post(self) -> None:
        """Test case for agent_post_tc_netem_tc_netem_post

        Set netem rules
        """
        pass

    def test_agent_post_tc_pacing_tc_pacing_post(self) -> None:
        """Test case for agent_post_tc_pacing_tc_pacing_post

        Set pacing rules
        """
        pass

    def test_agent_post_tune_endpoint_tune_post(self) -> None:
        """Test case for agent_post_tune_endpoint_tune_post

        Set node tuning settings
        """
        pass


if __name__ == '__main__':
    unittest.main()
