# coding: utf-8

"""
    The ESnet Janus container API

    REST endpoints for container provisioning and tuning

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from janus_py_client.models.check_token_response import CheckTokenResponse

class TestCheckTokenResponse(unittest.TestCase):
    """CheckTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckTokenResponse:
        """Test CheckTokenResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckTokenResponse`
        """
        model = CheckTokenResponse()
        if include_optional:
            return CheckTokenResponse(
                logged_in_as = ''
            )
        else:
            return CheckTokenResponse(
                logged_in_as = '',
        )
        """

    def testCheckTokenResponse(self):
        """Test CheckTokenResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
