# coding: utf-8

"""
    The ESnet Janus container API

    REST endpoints for container provisioning and tuning

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from janus_py_client.models.add_endpoint_request import AddEndpointRequest

class TestAddEndpointRequest(unittest.TestCase):
    """AddEndpointRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddEndpointRequest:
        """Test AddEndpointRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddEndpointRequest`
        """
        model = AddEndpointRequest()
        if include_optional:
            return AddEndpointRequest(
                edge_type = 56,
                name = '',
                public_url = '',
                type = 56,
                url = ''
            )
        else:
            return AddEndpointRequest(
                name = '',
                type = 56,
                url = '',
        )
        """

    def testAddEndpointRequest(self):
        """Test AddEndpointRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
