# coding: utf-8

"""
    The ESnet Janus container API

    REST endpoints for container provisioning and tuning

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from janus_py_client.models.exec_request import ExecRequest

class TestExecRequest(unittest.TestCase):
    """ExecRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExecRequest:
        """Test ExecRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExecRequest`
        """
        model = ExecRequest()
        if include_optional:
            return ExecRequest(
                cmd = [
                    ''
                    ],
                attach = True,
                container = '',
                node = '',
                start = True,
                tty = True
            )
        else:
            return ExecRequest(
                cmd = [
                    ''
                    ],
                container = '',
                node = '',
        )
        """

    def testExecRequest(self):
        """Test ExecRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
