# coding: utf-8

"""
    The ESnet Janus container API

    REST endpoints for container provisioning and tuning

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProfileResponse(BaseModel):
    """
    ProfileResponse
    """ # noqa: E501
    is_modified: Optional[StrictBool] = Field(default=None, description="Include timestamps in logs")
    is_system: Optional[StrictBool] = Field(default=None, description="Include timestamps in logs")
    name: StrictStr = Field(description="Name of the profile")
    on_disk: Optional[StrictBool] = Field(default=None, description="Include timestamps in logs")
    settings: Dict[str, Any] = Field(description="Configuration settings for the profile")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["is_modified", "is_system", "name", "on_disk", "settings"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProfileResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if is_modified (nullable) is None
        # and model_fields_set contains the field
        if self.is_modified is None and "is_modified" in self.model_fields_set:
            _dict['is_modified'] = None

        # set to None if is_system (nullable) is None
        # and model_fields_set contains the field
        if self.is_system is None and "is_system" in self.model_fields_set:
            _dict['is_system'] = None

        # set to None if on_disk (nullable) is None
        # and model_fields_set contains the field
        if self.on_disk is None and "on_disk" in self.model_fields_set:
            _dict['on_disk'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProfileResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "is_modified": obj.get("is_modified"),
            "is_system": obj.get("is_system"),
            "name": obj.get("name"),
            "on_disk": obj.get("on_disk"),
            "settings": obj.get("settings")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


