# coding: utf-8

"""
    The ESnet Janus container API

    REST endpoints for container provisioning and tuning

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class QoSAgent(BaseModel):
    """
    QoSAgent
    """ # noqa: E501
    container: Optional[StrictStr] = Field(default=None, description="Network interface name")
    corrupt: Optional[StrictStr] = Field(default=None, description="Network interface name")
    delay: Optional[StrictStr] = Field(default=None, description="Network interface name")
    dport: Optional[StrictStr] = Field(default=None, description="Network interface name")
    interface: Optional[StrictStr] = Field(default=None, description="Network interface name")
    ip: Optional[StrictStr] = Field(default=None, description="Network interface name")
    limit: Optional[StrictStr] = Field(default=None, description="Network interface name")
    loss: Optional[StrictStr] = Field(default=None, description="Network interface name")
    rate: Optional[StrictStr] = Field(default=None, description="Network interface name")
    reordering: Optional[StrictStr] = Field(default=None, description="Network interface name")
    __properties: ClassVar[List[str]] = ["container", "corrupt", "delay", "dport", "interface", "ip", "limit", "loss", "rate", "reordering"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QoSAgent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if container (nullable) is None
        # and model_fields_set contains the field
        if self.container is None and "container" in self.model_fields_set:
            _dict['container'] = None

        # set to None if corrupt (nullable) is None
        # and model_fields_set contains the field
        if self.corrupt is None and "corrupt" in self.model_fields_set:
            _dict['corrupt'] = None

        # set to None if delay (nullable) is None
        # and model_fields_set contains the field
        if self.delay is None and "delay" in self.model_fields_set:
            _dict['delay'] = None

        # set to None if dport (nullable) is None
        # and model_fields_set contains the field
        if self.dport is None and "dport" in self.model_fields_set:
            _dict['dport'] = None

        # set to None if interface (nullable) is None
        # and model_fields_set contains the field
        if self.interface is None and "interface" in self.model_fields_set:
            _dict['interface'] = None

        # set to None if ip (nullable) is None
        # and model_fields_set contains the field
        if self.ip is None and "ip" in self.model_fields_set:
            _dict['ip'] = None

        # set to None if limit (nullable) is None
        # and model_fields_set contains the field
        if self.limit is None and "limit" in self.model_fields_set:
            _dict['limit'] = None

        # set to None if loss (nullable) is None
        # and model_fields_set contains the field
        if self.loss is None and "loss" in self.model_fields_set:
            _dict['loss'] = None

        # set to None if rate (nullable) is None
        # and model_fields_set contains the field
        if self.rate is None and "rate" in self.model_fields_set:
            _dict['rate'] = None

        # set to None if reordering (nullable) is None
        # and model_fields_set contains the field
        if self.reordering is None and "reordering" in self.model_fields_set:
            _dict['reordering'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QoSAgent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "container": obj.get("container"),
            "corrupt": obj.get("corrupt"),
            "delay": obj.get("delay"),
            "dport": obj.get("dport"),
            "interface": obj.get("interface"),
            "ip": obj.get("ip"),
            "limit": obj.get("limit"),
            "loss": obj.get("loss"),
            "rate": obj.get("rate"),
            "reordering": obj.get("reordering")
        })
        return _obj


