# coding: utf-8

"""
    The ESnet Janus container API

    REST endpoints for container provisioning and tuning

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from janus_py_client.models.instances_inner import InstancesInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SessionRequest(BaseModel):
    """
    SessionRequest
    """ # noqa: E501
    arguments: Optional[StrictStr] = Field(default=None, description="Comma separated list of fields to return")
    constraints: Optional[Dict[str, Any]] = Field(default=None, description="Resource and scheduling constraints")
    image: StrictStr = Field(description="Docker image to run")
    instances: List[InstancesInner] = Field(description="List of instances or node names to deploy")
    kwargs: Optional[Dict[str, Any]] = Field(default=None, description="Additional docker kwargs")
    name: Optional[StrictStr] = Field(default=None, description="Comma separated list of fields to return")
    overrides: Optional[Dict[str, Any]] = Field(default=None, description="Profile overrides specific to this session")
    profile: StrictStr = Field(description="Host profile defining deployment parameters")
    remove_container: Optional[StrictBool] = Field(default=None, description="Automatically remove container on exit")
    __properties: ClassVar[List[str]] = ["arguments", "constraints", "image", "instances", "kwargs", "name", "overrides", "profile", "remove_container"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SessionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in instances (list)
        _items = []
        if self.instances:
            for _item_instances in self.instances:
                if _item_instances:
                    _items.append(_item_instances.to_dict())
            _dict['instances'] = _items
        # set to None if arguments (nullable) is None
        # and model_fields_set contains the field
        if self.arguments is None and "arguments" in self.model_fields_set:
            _dict['arguments'] = None

        # set to None if constraints (nullable) is None
        # and model_fields_set contains the field
        if self.constraints is None and "constraints" in self.model_fields_set:
            _dict['constraints'] = None

        # set to None if kwargs (nullable) is None
        # and model_fields_set contains the field
        if self.kwargs is None and "kwargs" in self.model_fields_set:
            _dict['kwargs'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if overrides (nullable) is None
        # and model_fields_set contains the field
        if self.overrides is None and "overrides" in self.model_fields_set:
            _dict['overrides'] = None

        # set to None if remove_container (nullable) is None
        # and model_fields_set contains the field
        if self.remove_container is None and "remove_container" in self.model_fields_set:
            _dict['remove_container'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SessionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "arguments": obj.get("arguments"),
            "constraints": obj.get("constraints"),
            "image": obj.get("image"),
            "instances": [InstancesInner.from_dict(_item) for _item in obj["instances"]] if obj.get("instances") is not None else None,
            "kwargs": obj.get("kwargs"),
            "name": obj.get("name"),
            "overrides": obj.get("overrides"),
            "profile": obj.get("profile"),
            "remove_container": obj.get("remove_container")
        })
        return _obj


